
cloudflare:
  ip_list:
    url: 'https://anycast.freecdn.workers.dev/'
    from_file: ip_list.txt
  test:
    max_ip: -1 # -1 unlimit, use all
    ping_thread: 100
    ping_count: 2
    speed_test_count: 1
    speed_start: 5000
    speed_end: 50000
    host: 'speed.cloudflare.com'
    path: '/__down?bytes=1000000000'
    download_chunk: 1024
    download_size: 10485760 # test download data size
    download_time: 10 # seconds, size and time reach on will end download

  result:
    select_count: 20 # ip list count after ping result to test speed

  log:
    ip_list: true
    ping: false
    sorted_ping_list: true
    speed: true
    sorted_speed_list: true

openclash:
  dns: 1.1.1.1
  use_ip: 3
  uuid: uuid
  ws-path: /path/
  host: host
  alterId: 0

