# Generated by Django 3.1.2 on 2020-10-20 07:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='JobRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('time', models.DateTimeField()),
                ('status', models.IntegerField()),
                ('log', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TesterJobSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=50)),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('cf_ip_list_url', models.CharField(max_length=255)),
                ('cf_ip_list_from_file', models.CharField(max_length=255)),
                ('max_ip', models.IntegerField(default=-1)),
                ('ping_thread', models.IntegerField(default=100)),
                ('ping_count', models.IntegerField(default=3)),
                ('speed_test_count', models.IntegerField(default=3)),
                ('speed_host', models.CharField(default='speed.cloudflare.com', max_length=255)),
                ('speed_url', models.CharField(default='/__down?bytes=1000000000', max_length=255)),
                ('download_chunk', models.IntegerField(default=1024)),
                ('download_size', models.IntegerField(default=10485760)),
                ('download_time', models.IntegerField(default=10)),
                ('select_count', models.IntegerField(default=10)),
                ('log_ip_list', models.BooleanField(default=False)),
                ('log_ping', models.BooleanField(default=False)),
                ('log_sorted_ping_list', models.BooleanField(default=False)),
                ('log_speed', models.BooleanField(default=False)),
                ('log_sorted_speed_list', models.BooleanField(default=False)),
                ('oc_dns', models.CharField(default='114.114.114.114', max_length=16)),
                ('oc_use_ip', models.IntegerField(default=3)),
                ('oc_uuid', models.CharField(max_length=64)),
                ('oc_ws_path', models.CharField(max_length=255)),
                ('oc_host', models.CharField(max_length=16)),
                ('oc_alert_id', models.IntegerField(default=3)),
            ],
        ),
    ]
