# Generated by Django 3.1.2 on 2020-10-20 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobEnv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('curent_job', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='TesterJobSetting',
            new_name='JobSetting',
        ),
        migrations.DeleteModel(
            name='JobNumber',
        ),
    ]
