# Generated by Django 3.1.2 on 2020-10-21 07:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0002_auto_20201020_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobenv',
            name='activate_job_setting',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='jobenv',
            name='curent_job',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='jobenv',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='jobsetting',
            name='cf_ip_list_from_file',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='jobsetting',
            name='oc_uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
