# Generated by Django 3.1.2 on 2020-10-24 02:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0003_auto_20201021_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenclashTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=50)),
                ('template', models.TextField(default='')),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='jobenv',
            name='activate_open_clash_template',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='jobrecord',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
