# Generated by Django 3.1.2 on 2020-10-29 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0004_auto_20201024_1035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobsetting',
            old_name='speed_url',
            new_name='speed_path',
        ),
    ]
