# Generated by Django 3.1.2 on 2020-10-29 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0006_auto_20201029_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsetting',
            name='oc_uuid',
            field=models.CharField(max_length=128),
        ),
    ]
