# Generated by Django 3.1.2 on 2020-11-03 05:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0007_auto_20201029_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulerSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduler_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('interval', models.IntegerField(default=3600)),
            ],
        ),
    ]
