# Generated by Django 3.1.2 on 2020-11-03 05:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0008_schedulersetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulersetting',
            name='scheduler_time',
            field=models.TimeField(default=datetime.datetime(2020, 11, 3, 5, 39, 20, 37174)),
        ),
    ]
