# Generated by Django 3.1.2 on 2020-11-13 01:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0009_auto_20201103_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobsetting',
            name='oc_alert_id',
        ),
        migrations.RemoveField(
            model_name='jobsetting',
            name='oc_host',
        ),
        migrations.RemoveField(
            model_name='jobsetting',
            name='oc_uuid',
        ),
        migrations.RemoveField(
            model_name='jobsetting',
            name='oc_ws_path',
        ),
        migrations.AlterField(
            model_name='schedulersetting',
            name='scheduler_time',
            field=models.TimeField(default=datetime.datetime(2020, 11, 13, 1, 48, 23, 174941)),
        ),
        migrations.CreateModel(
            name='V2RayConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=255)),
                ('uuid', models.CharField(max_length=128)),
                ('ws_path', models.CharField(max_length=255)),
                ('host', models.CharField(max_length=255)),
                ('alert_id', models.IntegerField(default=3)),
                ('job_setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tester.jobsetting')),
            ],
        ),
    ]
