# Generated by Django 3.1.2 on 2020-11-14 03:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0010_auto_20201113_0948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='v2rayconfig',
            name='alert_id',
        ),
        migrations.AddField(
            model_name='v2rayconfig',
            name='alter_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='jobsetting',
            name='cf_ip_list_from_file',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='jobsetting',
            name='cf_ip_list_url',
            field=models.CharField(default='https://anycast.freecdn.workers.dev/', max_length=255),
        ),
        migrations.AlterField(
            model_name='schedulersetting',
            name='scheduler_time',
            field=models.TimeField(default=datetime.datetime(2020, 11, 14, 3, 33, 24, 135843)),
        ),
        migrations.AlterField(
            model_name='v2rayconfig',
            name='alias',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='v2rayconfig',
            name='host',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='v2rayconfig',
            name='uuid',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='v2rayconfig',
            name='ws_path',
            field=models.CharField(default='', max_length=255),
        ),
    ]
